### ISSUE TITLE
Error: Unknown sensor 

### ISSUE THREAD

**Issue by iteayyy** [tmilliman/sirpy2#1]
Hi,  everyone,

I used this library to process the ASCAT (.sir) data of 2022 provided by Brigham Young University (BYU) website.

However, I encountered an unknown sensor error when using sir2geotiff, and I failed to finish the conversion.

I found that the "sensor" in head information of 2022 ASCAT data is "ASCAT-B (ASCAT on MetOp-B)", not included in the source code.

### The source code
```python
   # set name of landmask file based on sensor from file header
    if sensor.startswith("ASCAT-A"):
        landmask_file = "msf-{}.sir.lmask".format(region)
    elif sensor.startswith("OSCAT"):
        landmask_file = "oue-{}.sir.lmask".format(region)
    elif sensor.startswith("QuikScat L1B"):
        if product[2] == "e":
            landmask_file = "que-{}.sir.lmask".format(region)
        elif product[2] == "s":
            landmask_file = "qus-{}.sir.lmask".format(region)
    elif sensor.startswith("ERS-1/2"):
        landmask_file = "ers-{}.sir.lmask".format(region)
    elif sensor.startswith("NSCAT"):
        landmask_file = "nsc-{}.sir.lmask".format(region)
    elif sensor.startswith("SASS"):
        landmask_file = "sas-{}.sir.lmask".format(region)
    else:
        errmsg = "Unknown sensor"
        raise ValueError(errmsg)
```

**Comment by tmilliman** [comment]
I pushed a quick fix to the repo. Let me know if this works.  FWIW, the header "sensor" value changes again later in 2022 to "Sensor: ASCAT-T (Tandem ASCAT on MetOp-A/B".  I'm no longer working on this data as I've retired.

**Comment by iteayyy** [comment]
Thank you for your reply. 
The fix really works!
I appreciate it!

> I pushed a quick fix to the repo. Let me know if this works. FWIW, the header "sensor" value changes again later in 2022 to "Sensor: ASCAT-T (Tandem ASCAT on MetOp-A/B". I'm no longer working on this data as I've retired.
